# Generated by Django 5.0 on 2023-12-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('genre', models.CharField(choices=[('боевик', 'Боевик'), ('комедия', 'Комедия'), ('драма', 'Драма'), ('ужасы', 'Ужасы'), ('мелодрама', 'Мелодрама')], max_length=50)),
                ('director', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('trailer_url', models.URLField()),
                ('movie_url', models.URLField()),
                ('lang', models.CharField(choices=[('английский', 'Английский'), ('русский', 'Русский'), ('французский', 'Французский'), ('немецкий', 'Немецкий'), ('испанский', 'Испанский')], max_length=50)),
            ],
        ),
    ]
